[build]
  publish = "dist"
  command = "npm install && npm run build:production"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

# SPA Redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 