# Netlify config for marketing site (Vite)
[build]
  # Instala dependências de produção e desenvolvimento (evita erro `vite: not found`)
  command = "npm install --include=dev && npm run build"
  publish = "dist"

# Domain redirects
[[redirects]]
  from = "https://escolahabilidade.com/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://escolahabilidade.com.br/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 