# Configuração Netlify para Next.js 14
[build]
  base = "plataforma-ensino"
  command = "npm run build"
  publish = ".next"

[plugins]
  package = "@netlify/plugin-nextjs"

# (Opcional) Redirects extras podem ser adicionados abaixo 