# Netlify config for marketing site (Vite)
[build]
  # Instala dependências de produção e desenvolvimento (evita erro `vite: not found`)
  command = "npm install --include=dev && npm run build:production"
  publish = "dist"
  functions = "netlify/functions"

# Build específico para staging branch (debug mode)
[context.branch-deploy]
  command = "npm install --include=dev && DEBUG_BUILD=true npm run build"

[context.staging]
  command = "npm install --include=dev && DEBUG_BUILD=true npm run build"

# Configuração de desenvolvimento local
[dev]
  functions = "netlify/functions"
  functionsPort = 9999

# Domain redirects
[[redirects]]
  from = "https://escolahabilidade.com/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://escolahabilidade.com.br/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.escolahabilidade.com.br/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for HTML pages (1 hour)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

# Cache headers for static assets (1 year)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for images (1 week)
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# SEO Local pages redirects
[[redirects]]
  from = "/cursos-florianopolis"
  to = "/cursos-florianopolis.html"
  status = 200

[[redirects]]
  from = "/cursos-sao-jose"
  to = "/cursos-sao-jose.html"
  status = 200

[[redirects]]
  from = "/cursos-palhoca"
  to = "/cursos-palhoca.html"
  status = 200

# SSG fallback - only for non-existing pages  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404