# Netlify config for marketing site (Vite)
[build]
  # Instala dependências de produção e desenvolvimento (evita erro `vite: not found`)
  command = "npm install --include=dev && npm run build"
  publish = "dist"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 