# Netlify config for marketing site (Vite)
[build]
  # Instala dependências de produção e desenvolvimento (evita erro `vite: not found`)
  command = "npm install --include=dev && npm run build"
  publish = "dist"

# Domain redirects
[[redirects]]
  from = "https://escolahabilidade.com/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://escolahabilidade.com.br/*"
  to = "https://www.escolahabilidade.com/:splat"
  status = 301
  force = true

# Page redirects
[[redirects]]
  from = "/cursos"
  to = "/#cursos"
  status = 301

# SPA redirect - exclude static assets
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = "!(/images/*,/assets/*,*.js,*.css,*.png,*.jpg,*.jpeg,*.gif,*.svg,*.webp,*.ico,*.woff,*.woff2,*.ttf,*.eot,*.pdf,*.txt,*.xml,*.json,*.map)"} 