# Netlify config para plataforma Next.js
[build]
  command = "npm run build"
  publish = ".next"
  
# Serverless function configuration
[build.environment]
  NODE_VERSION = "18"

# Headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 