# Netlify config para plataforma Next.js
[build]
  command = "npm run build"
  publish = ".next"
  
# Environment configuration
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Use Essential Next.js plugin for better compatibility
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 